[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
odv_escrow = "4TVVaLhxNsoW82qhRiA9Fmspg4RUq26QvcmczW1JqijA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/**/*.js"
