[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
odv_escrow = "2NZKEk8zk47UAc27f7DScFgxpqyy22VptWVwBUjFfQxC"

[programs.testnet]
odv_escrow = "2NZKEk8zk47UAc27f7DScFgxpqyy22VptWVwBUjFfQxC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/**/*.js"
