import { Connection, PublicKey, Transaction, TransactionInstruction } from '@solana/web3.js';
import { getCampaignPDA, ODV_ESCROW_PROGRAM_ID, Campaign } from './program';
import * as borsh from '@coral-xyz/borsh';

// Borsh schema for Campaign account (simplified)
const campaignSchema = borsh.struct([
    borsh.publicKey('creator'),
    borsh.u64('goal'),
    borsh.u64('raised'),
    borsh.i64('deadline'),
    borsh.u8('currentMilestoneIndex'),
    borsh.u8('bump'),
    // Note: In a full implementation, we'd deserialize the Vec<Milestone> as well
    // For MVP, we'll just check if the account exists
]);

/**
 * Check if a campaign has been initialized for a creator
 */
export async function isCampaignInitialized(
    connection: Connection,
    creatorPublicKey: PublicKey
): Promise<boolean> {
    const [campaignPDA] = getCampaignPDA(creatorPublicKey);

    try {
        const accountInfo = await connection.getAccountInfo(campaignPDA);
        return accountInfo !== null;
    } catch (error) {
        console.error('Error checking campaign:', error);
        return false;
    }
}

/**
 * Get campaign state from blockchain
 */
export async function getCampaignState(
    connection: Connection,
    creatorPublicKey: PublicKey
): Promise<Campaign | null> {
    const [campaignPDA] = getCampaignPDA(creatorPublicKey);

    try {
        const accountInfo = await connection.getAccountInfo(campaignPDA);
        if (!accountInfo) return null;

        // For MVP, we'll return a simplified version
        // In production, you'd properly deserialize the entire account with borsh
        const data = accountInfo.data;

        // Basic deserialization (first 72 bytes)
        const creator = new PublicKey(data.slice(0, 32));
        const goal = Number(data.readBigUInt64LE(32));
        const raised = Number(data.readBigUInt64LE(40));
        const deadline = Number(data.readBigInt64LE(48));
        const currentMilestoneIndex = data[56];
        const bump = data[57];

        return {
            creator,
            goal,
            raised,
            deadline,
            currentMilestoneIndex,
            milestones: [], // Would need full borsh deserialization
            bump,
        };
    } catch (error) {
        console.error('Error fetching campaign state:', error);
        return null;
    }
}

/**
 * Create instruction to initialize a campaign
 * Note: This is a placeholder. In production, you'd use the generated Anchor client
 */
export async function createInitializeCampaignInstruction(
    creatorPublicKey: PublicKey,
    goal: number,
    deadline: number,
    milestones: Array<{ title: string; amount: number }>
): Promise<TransactionInstruction> {
    const [campaignPDA] = getCampaignPDA(creatorPublicKey);

    // This would normally be generated by Anchor
    // For MVP, we're creating a simplified version
    const instructionData = Buffer.from([
        0, // Instruction index for 'initialize'
        ...new Uint8Array(new BigUint64Array([BigInt(goal)]).buffer),
        ...new Uint8Array(new BigInt64Array([BigInt(deadline)]).buffer),
        // Milestones would be serialized here
    ]);

    return new TransactionInstruction({
        keys: [
            { pubkey: campaignPDA, isSigner: false, isWritable: true },
            { pubkey: creatorPublicKey, isSigner: true, isWritable: true },
            { pubkey: new PublicKey('11111111111111111111111111111111'), isSigner: false, isWritable: false }, // System Program
        ],
        programId: ODV_ESCROW_PROGRAM_ID,
        data: instructionData,
    });
}
